const admin_appointmentsData = [
    {
        id: 1,
        consultantName: "Dr. John Smith",
        clientName: "John Doe",
        date: "2024-10-20",
        start: { time: "04:00", period: "PM" },
        end: { time: "06:00", period: "PM" },
        status: "Upcoming",
    },
    {
        id: 2,
        consultantName: "Dr. Jane Doe",
        clientName: "Alice",
        date: "2024-10-21",
        start: { time: "10:00", period: "AM" },
        end: { time: "11:00", period: "AM" },
        status: "Today",
    },
    {
        id: 3,
        consultantName: "Dr. Brown",
        clientName: "Bob",
        date: "2024-10-19",
        start: { time: "02:00", period: "PM" },
        end: { time: "03:00", period: "PM" },
        status: "Upcoming",
    },
    {
        id: 4,
        consultantName: "Dr. Emily Clark",
        clientName: "Charlie",
        date: "2024-10-22",
        start: { time: "09:00", period: "AM" },
        end: { time: "10:00", period: "AM" },
        status: "Upcoming",
    },
    {
        id: 5,
        consultantName: "Dr. Michael Johnson",
        clientName: "David",
        date: "2024-10-23",
        start: { time: "01:00", period: "PM" },
        end: { time: "02:00", period: "PM" },
        status: "Today",
    },
    {
        id: 6,
        consultantName: "Dr. Sarah Lee",
        clientName: "Eve",
        date: "2024-10-18",
        start: { time: "03:00", period: "PM" },
        end: { time: "04:00", period: "PM" },
        status: "Complete",
    },
];

export default admin_appointmentsData;