const applicationsData = [
    {
        id: 1,
        firstName: "John",
        lastName: "Doe",
        username: "johndoe",
        age: 35,
        address: "123 Main St",
        city: "New York",
        district: "Manhattan",
        specialization: "Psychiatrist",
        contact: "john.doe@example.com",
        isPsychiatrist: true,
        medicalQualification: "medical_qualification.pdf",
        profileImg: "profile_img.jpg",
        nic: "nic.pdf",
        degreeTranscript: "degree_transcript.pdf",
        experience: "5 years of experience in mental health counseling.",
        signature: "signature.png",
      },
      {
        id: 2,
        firstName: "Jane",
        lastName: "Smith",
        username: "janesmith",
        age: 40,
        address: "456 Elm St",
        city: "Los Angeles",
        district: "Hollywood",
        specialization: "Therapist",
        contact: "jane.smith@example.com",
        isPsychiatrist: false,
        profileImg: "profile_img.jpg",
        nic: "nic.pdf",
        degreeTranscript: "degree_transcript.pdf",
        experience: "10 years of experience in therapy.",
        signature: "signature.png",
      },
      {
        id: 3,
        firstName: "Jane",
        lastName: "Smith",
        username: "janesmith",
        age: 40,
        address: "456 Elm St",
        city: "Los Angeles",
        district: "Hollywood",
        specialization: "Therapist",
        contact: "jane.smith@example.com",
        isPsychiatrist: false,
        profileImg: "profile_img.jpg",
        nic: "nic.pdf",
        degreeTranscript: "degree_transcript.pdf",
        experience: "10 years of experience in therapy.",
        signature: "signature.png",
      },
];

export default applicationsData;